"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WeatherForecastToJSON = exports.WeatherForecastFromJSONTyped = exports.WeatherForecastFromJSON = void 0;
const runtime_1 = require("../runtime");
function WeatherForecastFromJSON(json) {
    return WeatherForecastFromJSONTyped(json, false);
}
exports.WeatherForecastFromJSON = WeatherForecastFromJSON;
function WeatherForecastFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'date': !(0, runtime_1.exists)(json, 'date') ? undefined : (new Date(json['date'])),
        'temperatureC': !(0, runtime_1.exists)(json, 'temperatureC') ? undefined : json['temperatureC'],
        'temperatureF': !(0, runtime_1.exists)(json, 'temperatureF') ? undefined : json['temperatureF'],
        'summary': !(0, runtime_1.exists)(json, 'summary') ? undefined : json['summary'],
    };
}
exports.WeatherForecastFromJSONTyped = WeatherForecastFromJSONTyped;
function WeatherForecastToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'temperatureC': value.temperatureC,
        'summary': value.summary,
    };
}
exports.WeatherForecastToJSON = WeatherForecastToJSON;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV2VhdGhlckZvcmVjYXN0LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vLi4vc3JjL21vZGVscy9XZWF0aGVyRm9yZWNhc3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLG9CQUFvQjtBQUNwQixvQkFBb0I7QUFDcEI7Ozs7Ozs7Ozs7R0FVRzs7O0FBRUgsd0NBQStDO0FBaUMvQyxTQUFnQix1QkFBdUIsQ0FBQyxJQUFTO0lBQzdDLE9BQU8sNEJBQTRCLENBQUMsSUFBSSxFQUFFLEtBQUssQ0FBQyxDQUFDO0FBQ3JELENBQUM7QUFGRCwwREFFQztBQUVELFNBQWdCLDRCQUE0QixDQUFDLElBQVMsRUFBRSxtQkFBNEI7SUFDaEYsSUFBSSxDQUFDLElBQUksS0FBSyxTQUFTLENBQUMsSUFBSSxDQUFDLElBQUksS0FBSyxJQUFJLENBQUMsRUFBRTtRQUN6QyxPQUFPLElBQUksQ0FBQztLQUNmO0lBQ0QsT0FBTztRQUVILE1BQU0sRUFBRSxDQUFDLElBQUEsZ0JBQU0sRUFBQyxJQUFJLEVBQUUsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDLFNBQVMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLElBQUksQ0FBQyxJQUFJLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQztRQUNwRSxjQUFjLEVBQUUsQ0FBQyxJQUFBLGdCQUFNLEVBQUMsSUFBSSxFQUFFLGNBQWMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxTQUFTLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxjQUFjLENBQUM7UUFDaEYsY0FBYyxFQUFFLENBQUMsSUFBQSxnQkFBTSxFQUFDLElBQUksRUFBRSxjQUFjLENBQUMsQ0FBQyxDQUFDLENBQUMsU0FBUyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsY0FBYyxDQUFDO1FBQ2hGLFNBQVMsRUFBRSxDQUFDLElBQUEsZ0JBQU0sRUFBQyxJQUFJLEVBQUUsU0FBUyxDQUFDLENBQUMsQ0FBQyxDQUFDLFNBQVMsQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLFNBQVMsQ0FBQztLQUNwRSxDQUFDO0FBQ04sQ0FBQztBQVhELG9FQVdDO0FBRUQsU0FBZ0IscUJBQXFCLENBQUMsS0FBOEI7SUFDaEUsSUFBSSxLQUFLLEtBQUssU0FBUyxFQUFFO1FBQ3JCLE9BQU8sU0FBUyxDQUFDO0tBQ3BCO0lBQ0QsSUFBSSxLQUFLLEtBQUssSUFBSSxFQUFFO1FBQ2hCLE9BQU8sSUFBSSxDQUFDO0tBQ2Y7SUFDRCxPQUFPO1FBRUgsTUFBTSxFQUFFLEtBQUssQ0FBQyxJQUFJLEtBQUssU0FBUyxDQUFDLENBQUMsQ0FBQyxTQUFTLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxXQUFXLEVBQUUsQ0FBQztRQUN6RSxjQUFjLEVBQUUsS0FBSyxDQUFDLFlBQVk7UUFDbEMsU0FBUyxFQUFFLEtBQUssQ0FBQyxPQUFPO0tBQzNCLENBQUM7QUFDTixDQUFDO0FBYkQsc0RBYUMifQ==