/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { WeatherForecast } from '../models';
/**
 *
 */
export declare class WeatherForecastApi extends runtime.BaseAPI {
    /**
     */
    weatherForecastGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<WeatherForecast>>>;
    /**
     */
    weatherForecastGet(initOverrides?: RequestInit): Promise<Array<WeatherForecast>>;
}
